FROM golang:1.21-alpine

WORKDIR /app

# Копируем общие пакеты
COPY common/ /app/common/
COPY worker/ /app/worker/

WORKDIR /app/worker

RUN go mod download
RUN go build -o worker

EXPOSE 8080

CMD ["./worker"]
