services:
  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - WORKER_URLS=http://worker1:8080,http://worker2:8080,http://worker3:8080
    networks:
      - hash-cracker-network

  worker1:
    build:
      context: ./worker
      dockerfile: Dockerfile
    networks:
      - hash-cracker-network

  worker2:
    build:
      context: ./worker
      dockerfile: Dockerfile
    networks:
      - hash-cracker-network

  worker3:
    build:
      context: ./worker
      dockerfile: Dockerfile
    networks:
      - hash-cracker-network

networks:
  hash-cracker-network:
    driver: bridge
